### ISSUE TITLE
Assignment for July 13

### ISSUE THREAD

**Issue by stephaniehicks** [stephaniehicks/benchmark-kmeans#2]
Shenzhi's assignment for July 13

- [x] Use the code in [this R Markdown](https://github.com/stephaniehicks/benchmark-kmeans/blob/master/analyses/R/2018-07-Zeiseldata.Rmd) to open [this dataset](https://github.com/stephaniehicks/benchmark-kmeans/tree/master/data) in R
- [x] Read about how to pre-process single cell gene expression data using the [scater Bioconductor package](https://bioconductor.org/packages/release/bioc/html/scater.html) by working through the [quality control tutorial](https://bioconductor.org/packages/release/bioc/vignettes/scater/inst/doc/vignette-qc.html) and normalization on the webpage. 
- [x] Apply quality control metrics to dataset
- [x] Save the preprocessed and normalized count table as a CSV file and open in Python 
- [x] Run t-SNE and PCA on dataset. Remember, you must remove the mean for each gene before running PCA. 
- [x] Try running k-means on the top 5 PCs. 
- [x] Save dataset as an HDF5 file and learn about how Python loads the dataset (does it load it all into memory?)
- [x] Compare Kmeans to MiniBatchKMeans in Python [see this tutorial](http://scikit-learn.org/stable/auto_examples/cluster/plot_mini_batch_kmeans.html#sphx-glr-auto-examples-cluster-plot-mini-batch-kmeans-py).

**Comment by ShenzhiS** [comment]
R code for preprocessing: benchmark-kmeans/analyses/R/MouseCortex-Preprocessing.R
Python for comparing kmeans and minibatchkmeans:
benchmark-kmeans/analyses/Python/MiniBatchKMeansCompare.ipynb
